name: Build

on:
    push:
        branches:
            - "*"
        paths-ignore:
            - ".gitignore"
    pull_request:
        branches:
            - "*"
        paths-ignore:
            - ".gitignore"
    workflow_dispatch:
permissions: write-all
jobs:
    build:
        runs-on: ubuntu-latest
        name: "Build and test"
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   uses: ./.github/actions/setup-normal-workspace
            -   name: Build with Gradle
                run: ./gradlew assemble -x test --stacktrace
            -   uses: actions/upload-artifact@v4
                name: Upload development build
                with:
                    name: "Development Build"
                    path: build/libs/*.jar
            -   name: Test with Gradle
                run: ./gradlew test
            -   uses: actions/upload-artifact@v4
                name: "Upload test report"
                if: ${{ !cancelled() }}
                with:
                    name: "Test Results"
                    path: versions/1.8.9/build/reports/tests/test/
    detekt:
        name: Run detekt
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   uses: ./.github/actions/setup-normal-workspace
            # detektMain is a LOT slower than detekt, but it does type analysis
            -   name: Run detekt main (w/typing analysis)
                run: |
                    ./gradlew detektMain --stacktrace
            -   name: Annotate detekt failures
                if: ${{ !cancelled() }}
                run: |
                    chmod +x .github/scripts/process_detekt_sarif.sh
                    ./.github/scripts/process_detekt_sarif.sh versions/1.8.9/build/reports/detekt/main.sarif

    detekt_comment:
        name: Comment detekt failures on PR
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'pull_request' && steps.detekt.outcome == 'failure' }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Process detekt SARIF and create comment
              run: |
                  chmod +x .github/scripts/process_detekt_sarif.sh
                  ./.github/scripts/process_detekt_sarif.sh versions/1.8.9/build/reports/detekt/main.sarif > detekt_output.txt

                  # Extract the Detekt output
                  DETEKT_OUTPUT=$(cat detekt_output.txt)

                  # Format the message for PR comments
                  COMMENT="### One or more Detekt Failures were detekted: \n\n"
                  while read -r line; do
                      FILE_PATH=$(echo "$line" | cut -d' ' -f2)
                      LINE_NUMBER=$(echo "$line" | grep -oP "#L\K\d+")
                      COMMENT+="- [ ] [$FILE_PATH#L$LINE_NUMBER](${{ github.server_url }}/$GITHUB_REPOSITORY/blob/$GITHUB_SHA/$FILE_PATH#L$LINE_NUMBER): $line\n"
                  done <<< "$DETEKT_OUTPUT"

                  # Post comment on PR
                  curl -s -X POST \
                      -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Content-Type: application/json" \
                      --data "{ \"body\": \"$COMMENT\" }" \
                      ${{ github.event.pull_request.comments_url }}

    preprocess:
        runs-on: ubuntu-latest
        name: "Build multi version"
        env:
            SKIP_DETEKT: "true"
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   uses: ./.github/actions/setup-normal-workspace
            -   name: Enable preprocessor
                run: |
                    mkdir -p .gradle
                    echo skyhanni.multi-version=preprocess-only > .gradle/private.properties
            -   name: Build with Gradle
                run: ./gradlew build --stacktrace
